export interface Product {
    [val: string]: string | number | undefined,
    key: string,
    name: string,
    brand: string,
    memory?: number,
    color?: string,
    processor?: string,
    graphics?: string,
    screen?: string,
    cores?: string,
    cache?: string,
    screenSize?: string,
    energyClass?: string,
    type?: string,
    price: number,
    img: string,
    scdImg?: string,
    category: string,
    _id: string
}